export { default as Navbar } from './NavBar'
export { default as Footer } from './Footer'
export { default as IndexCaroulsel } from './IndexCaroulsel'
export { default as IndexIcons } from './IndexIcons'
export { default as CatalogDisplayer } from './CatalogDisplayer'
export { default as ProductCard } from './ProductCard'